// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// เว็บ/PWA — ใช้สำหรับแจ้งเตือน Web Push (iPhone ต้องเพิ่มลงหน้าจอโฮมก่อน)
  /// ค่าพวกนี้ไม่ใช่ความลับ (ฝังอยู่ในหน้าเว็บอยู่แล้ว) ความปลอดภัยอยู่ที่ Firebase Rules
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXm7OkxFLW6YSaLaFy-_1Zib2yIZjhwfc',
    appId: '1:52873487111:web:a9ef21ee2d93ce3ce65ba2',
    messagingSenderId: '52873487111',
    projectId: 'phee-ngern',
    authDomain: 'phee-ngern.firebaseapp.com',
    storageBucket: 'phee-ngern.firebasestorage.app',
    measurementId: 'G-QJ07T3K293',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPhVfmQsKrsppagYaj_fv_5NY8Axds788',
    appId: '1:52873487111:android:1058852022d83e7fe65ba2',
    messagingSenderId: '52873487111',
    projectId: 'phee-ngern',
    storageBucket: 'phee-ngern.firebasestorage.app',
  );
}
